---
title: "Supplementary Figure S5. ARTEMIS-DELFI scores correlate with Ki-67 proliferation indices in tumor samples"
site: workflowr::wflow_site
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
editor_options:
  chunk_output_type: console
---

```{r caching, echo=FALSE}
knitr::opts_chunk$set(autodep = TRUE)
```

```{r packages, message=FALSE, warning=FALSE, echo = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table)
library(openxlsx)
library(RColorBrewer)
library(ggpubr)
library(here)
```

```{r load.data, echo = FALSE, message=FALSE, warning=FALSE}
ann = read.xlsx('../data/ki67.xlsx', sheet = 'clean') %>% 
      select(1,3) %>% 
      dplyr::rename(alternate_id = Alternate_ID, ki67 = Ki67.Simplified)

load('../output/02-artemis-delfi/scores.rda')
load('../output/01-rbrain/metadata.rda')

ann$alternate_id = gsub("CGCNS21P_1", "CGCNS21P_2", ann$alternate_id)
ann$alternate_id = gsub("CGCNS22P_1", "CGCNS22P_2", ann$alternate_id)
ann$alternate_id = gsub("CGCNS64P_1", "CGCNS64P_2", ann$alternate_id)
ann$alternate_id = gsub("CGCNS67P_1", "CGCNS67P_2", ann$alternate_id)
ann$alternate_id = gsub("CGCNS71P_1", "CGCNS71P_2", ann$alternate_id)


pd = merge(ann, scores %>% select(id, artemis.delfi), all.x = TRUE, 
            by.x = 'alternate_id', by.y = 'id') %>% 
      filter(! is.na(artemis.delfi))

counts = pd %>% 
            group_by(ki67) %>% 
            tally() %>% 
            dplyr::rename(counts = n) %>% 
            unite("xlab", ki67:counts, sep = '\n(n=', remove = FALSE) %>% 
            mutate(xlab = paste0(xlab, ')')) %>% 
            select(ki67, xlab)

pd = merge(pd, counts, by = 'ki67', all.x = TRUE)
pd$ki67 = factor(pd$ki67, levels = c('<=20%', '>20%'))
pd = pd %>% arrange(ki67) %>% mutate(xlab = factor(xlab, levels = unique(xlab)))

pd = merge(pd, 
           metadata %>% select(alternate_id, pathology._simplified), all.x = TRUE,
           by= 'alternate_id')

```

```{r FigureS5, echo = FALSE, message=FALSE, warning=FALSE, fig.width=7, fig.height = 4, dev = c('png', 'pdf')}

ggplot(pd, aes(x = xlab, y = artemis.delfi)) + 
    geom_boxplot(outlier.color = NULL, width = 0.4) + 
    geom_jitter(width = 0.2) + stat_compare_means() + 
    theme_pubr() + 
    labs(x = 'Ki-67 Score', y = 'ARTEMIS-DELFI Score') + 
    theme(legend.position = 'right')


```
