---
title: "Supplementary Figure S4. Correlation of brain tumor size with ARTEMIS-DELFI scores"
author: ""
date: ''
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, message=FALSE, warning=FALSE, echo = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(ggfortify)
library(ggh4x)
library(ggpubr)
library(latex2exp)
library(data.table)
library(reshape2)
library(cowplot)
library(pROC)
library(here)
library(survival)
library(survminer)
library(patchwork)
library(finalfit)
library(openxlsx)
library(viridis)

```

```{r load_data, echo=FALSE, warning = FALSE}

base = fread('../output/02-artemis-delfi/Cross_Validation_scores.csv')
base$V1 = NULL

models = unique(base$model)
keep = c(models[grepl('ssl', models)], 'Cov_GBM', 'ARTEMIS_Ensemble', 'ARTEMIS_single_DELFI_SSLs_Ensemble')
base = base %>% filter(model %in% keep)

load('../output/01-rbrain/metadata.rda')

metadata = metadata %>% separate(col = 'alternate_id', sep = '_', into = c('prefix', 'suffix'), remove = FALSE)

base$id = gsub('CGCNS23P', 'CGCNS23P_1', base$id)
scores = merge(base, metadata %>% select(alternate_id, prefix), by.x = 'id', by.y = 'alternate_id')

#--------------------------------------#
size = read.xlsx('../data/tumor_size.xlsx',1)
colnames(size) = c('id', 'volume', 'score', 'metric')
size$score = NULL

# size$score = NULL
size = merge(size, scores %>% select(prefix, model, score),
             by.x ='id', by.y = 'prefix', all.x = TRUE)
#--------------------------------------#

```

```{r FigureS4, echo = FALSE, message = FALSE, warning=FALSE, , dev = c('png', 'pdf'), fig.height = 4, fig.width = 8}

p.ce = ggplot(size %>% filter(metric == "CE" & model == "ARTEMIS_single_DELFI_SSLs_Ensemble"), 
                    aes(x = volume, y = score)) + 
             geom_point() + 
             theme_pubr() + 
             labs(x = TeX(sprintf(r'($Volume (cm^3)$)')) ,  y = 'ARTEMIS-DELFI Score', 
                  title = 'Contrast Enhancement' ) + 
             stat_cor(label.x = 40, label.y = 0.5, color = 'navy' ) + 
            theme(plot.margin = margin(t = 0, b = 1.05, l = 0, r = 0, "cm"),
                  plot.title = element_text(hjust = 0.5))

p.flair = ggplot(size %>% filter(metric == "Flair" & model == "ARTEMIS_single_DELFI_SSLs_Ensemble"),  
                   aes(x = volume, y = score)) + 
             geom_point() + 
             theme_pubr() + 
             labs(x = TeX(sprintf(r'($Volume (cm^3)$)')) ,  y = 'ARTEMIS-DELFI Score', 
                  title = 'FLAIR' ) + 
             stat_cor(label.x = 150, label.y = 0.5, color = 'navy')+ 
            theme(plot.margin = margin(t = 0, b = 1.05, l = 0, r = 0, "cm"),
                  plot.title = element_text(hjust = 0.5))

part.b = cowplot::plot_grid(NULL,p.ce, p.flair, NULL, labels = c('', 'A', 'B', ''), ncol = 4, rel_widths = c(0.02, 1, 1, 0.02))
plot(part.b)

```
